// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_architecture/test/core/utils/helpers/api_call_helper_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_architecture/core/commundomain/entitties/based_api_result/api_result_model.dart'
    as _i3;
import 'package:flutter_architecture/core/utils/helpers/connectivity_helper/connectivity_checker_helper.dart'
    as _i2;
import 'package:flutter_architecture/core/utils/helpers/http_strategy_helper/http_request_strategy.dart'
    as _i7;
import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

import 'api_call_helper_test.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConnectivityCheckerHelper_0 extends _i1.SmartFake
    implements _i2.ConnectivityCheckerHelper {
  _FakeConnectivityCheckerHelper_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiResultModel_1<T> extends _i1.SmartFake
    implements _i3.ApiResultModel<T> {
  _FakeApiResultModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiCallHelperTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiCallHelperTest extends _i1.Mock implements _i4.ApiCallHelperTest {
  MockApiCallHelperTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ConnectivityCheckerHelper get connectivityCheckerHelper =>
      (super.noSuchMethod(
        Invocation.getter(#connectivityCheckerHelper),
        returnValue: _FakeConnectivityCheckerHelper_0(
          this,
          Invocation.getter(#connectivityCheckerHelper),
        ),
      ) as _i2.ConnectivityCheckerHelper);

  @override
  _i5.Future<void> initSharedDefaultHeader(
          [String? contentValue = r'application/json']) =>
      (super.noSuchMethod(
        Invocation.method(
          #initSharedDefaultHeader,
          [contentValue],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.ApiResultModel<_i6.Response>> makeRequest({
    required String? uri,
    required _i7.HttpRequestStrategy? httpRequestStrategy,
    Map<String, String>? headers = const {},
    Map<String, dynamic>? requestData = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeRequest,
          [],
          {
            #uri: uri,
            #httpRequestStrategy: httpRequestStrategy,
            #headers: headers,
            #requestData: requestData,
          },
        ),
        returnValue: _i5.Future<_i3.ApiResultModel<_i6.Response>>.value(
            _FakeApiResultModel_1<_i6.Response>(
          this,
          Invocation.method(
            #makeRequest,
            [],
            {
              #uri: uri,
              #httpRequestStrategy: httpRequestStrategy,
              #headers: headers,
              #requestData: requestData,
            },
          ),
        )),
      ) as _i5.Future<_i3.ApiResultModel<_i6.Response>>);
}
