// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_architecture/test/features/weather_info/data/datasources/weather_local_datasource_test/weather_datasources_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_architecture/features/weather_info/data/models/weather_info_remote_response_model/weather_info_response_model.dart'
    as _i5;
import 'package:flutter_architecture/features/weather_info/domain/entities/weather_remote_info_response_entity/weather_info_entity.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

import 'weather_datasources_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MockWeatherLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockWeatherLocalDataSource extends _i1.Mock
    implements _i2.MockWeatherLocalDataSource {
  MockMockWeatherLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.WeatherInfoEntity?> getLastWeatherInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastWeatherInfo,
          [],
        ),
        returnValue: _i3.Future<_i4.WeatherInfoEntity?>.value(),
      ) as _i3.Future<_i4.WeatherInfoEntity?>);

  @override
  _i3.Future<List<_i4.WeatherInfoEntity?>?> getAllLocalWeathers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllLocalWeathers,
          [],
        ),
        returnValue: _i3.Future<List<_i4.WeatherInfoEntity?>?>.value(),
      ) as _i3.Future<List<_i4.WeatherInfoEntity?>?>);

  @override
  void cacheWeatherInfo(
          _i5.WeatherInfoResponseModel? weatherInfoResponseModel) =>
      super.noSuchMethod(
        Invocation.method(
          #cacheWeatherInfo,
          [weatherInfoResponseModel],
        ),
        returnValueForMissingStub: null,
      );
}
