// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_architecture/test/features/weather_info/data/datasources/weather_remote_datasource_test/weather_datasources_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_architecture/core/commundomain/entitties/based_api_result/api_result_model.dart'
    as _i2;
import 'package:flutter_architecture/features/weather_info/data/models/weather_info_remote_response_model/weather_info_response_model.dart'
    as _i5;
import 'package:flutter_architecture/features/weather_info/utils/requests_models/weather_by_coordinates_request_model.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

import 'weather_datasources_mock.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResultModel_0<T> extends _i1.SmartFake
    implements _i2.ApiResultModel<T> {
  _FakeApiResultModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i3.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResultModel<_i5.WeatherInfoResponseModel?>>
      getWeatherDataByCoordinates(
              {_i6.WeatherByCoordinatesRequestModel?
                  weatherByCoordinatesRequestModel}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getWeatherDataByCoordinates,
              [],
              {
                #weatherByCoordinatesRequestModel:
                    weatherByCoordinatesRequestModel
              },
            ),
            returnValue: _i4.Future<
                    _i2.ApiResultModel<_i5.WeatherInfoResponseModel?>>.value(
                _FakeApiResultModel_0<_i5.WeatherInfoResponseModel?>(
              this,
              Invocation.method(
                #getWeatherDataByCoordinates,
                [],
                {
                  #weatherByCoordinatesRequestModel:
                      weatherByCoordinatesRequestModel
                },
              ),
            )),
          ) as _i4.Future<_i2.ApiResultModel<_i5.WeatherInfoResponseModel?>>);

  @override
  _i4.Future<
      _i2.ApiResultModel<_i5.WeatherInfoResponseModel?>> getWeatherDataByCity(
          {String? cityName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherDataByCity,
          [],
          {#cityName: cityName},
        ),
        returnValue:
            _i4.Future<_i2.ApiResultModel<_i5.WeatherInfoResponseModel?>>.value(
                _FakeApiResultModel_0<_i5.WeatherInfoResponseModel?>(
          this,
          Invocation.method(
            #getWeatherDataByCity,
            [],
            {#cityName: cityName},
          ),
        )),
      ) as _i4.Future<_i2.ApiResultModel<_i5.WeatherInfoResponseModel?>>);
}
